// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxJPBSluuj0XPxQznPm1NwLyNNzfJTQ4I',
    appId: '1:415276907886:web:eb52344c44697cb76c157f',
    messagingSenderId: '415276907886',
    projectId: 'flutter-firebase-ed96e',
    authDomain: 'flutter-firebase-ed96e.firebaseapp.com',
    storageBucket: 'flutter-firebase-ed96e.appspot.com',
    measurementId: 'G-ZM8TL0VLLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFaaQSHTbFLWZObjJ1JOpx3lamoXcAJQ',
    appId: '1:415276907886:android:cc2ba3c26d9ab10f6c157f',
    messagingSenderId: '415276907886',
    projectId: 'flutter-firebase-ed96e',
    storageBucket: 'flutter-firebase-ed96e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJTN3D3rfZ_gpYgBeaElafUCKLcbvrvHg',
    appId: '1:415276907886:ios:aea646cc2fb20d666c157f',
    messagingSenderId: '415276907886',
    projectId: 'flutter-firebase-ed96e',
    storageBucket: 'flutter-firebase-ed96e.appspot.com',
    iosClientId: '415276907886-fbusk5ved50v6c9p1ftqkh17tj0pnd2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJTN3D3rfZ_gpYgBeaElafUCKLcbvrvHg',
    appId: '1:415276907886:ios:aea646cc2fb20d666c157f',
    messagingSenderId: '415276907886',
    projectId: 'flutter-firebase-ed96e',
    storageBucket: 'flutter-firebase-ed96e.appspot.com',
    iosClientId: '415276907886-fbusk5ved50v6c9p1ftqkh17tj0pnd2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );
}
